version: '3.8'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hovy-monitor-dev
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  hovymonitor-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hovymonitor-api
    restart: always
    ports:
      - 6600:6600
    depends_on:
      - db
    links:
      - db
    environment:
      - BASE_URL=plantuml
    volumes:
      - /dev:/dev
    privileged: true

volumes:
  db:
    driver: local
